server:
  port: 8082

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5432/student_performance_students
    username: postgres
    password: varsha27
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: 4f1c1f2e9d9b6a7c4f1c1f2e9d9b6a7c4f1c1f2e9d9b6a7c4f1c1f2e9d9b6a7c
    expiration-ms: 86400000
